//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_Ly_TV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuPhat
    {
        public int Id { get; set; }
        public string MaPhieuPhat { get; set; }
        public string NhanVien { get; set; }
        public string NgayLapPhieu { get; set; }
        public Nullable<int> TienPhat { get; set; }
        public string MaDocGia { get; set; }
        public string LyDoPhat { get; set; }
        public string MaPhieuMuon { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual PhieuMuon PhieuMuon1 { get; set; }
        public virtual PhieuMuon PhieuMuon2 { get; set; }
    }
}
